# Generated by Django 3.0.4 on 2020-03-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSigtuna', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalinfo',
            name='history',
            field=models.TextField(null=True),
        ),
    ]
